calibration:
  number_phases: 16
  average_intensity: 0.5
  modulation_intensity: 0.5
  shading_threshold: 60
phase_shift_with_tpu:
  number_phases: 12
  average_intensity: 0.6
  modulation_intensity: 0.4
  shading_threshold: 60
two_plus_one_with_tpu:
  number_phases: 12
  average_intensity: 0.6
  modulation_intensity: 0.4
  shading_threshold: 60
