calibration:
  # Calibration uses the same Phase Shift with TPU codec, but with different settings
  number_phases_horizontal: 25
  number_phases_vertical: 16
  average_intensity: 0.5
  modulation_intensity: 0.5
  shading_threshold: 25
  disable_lens_distortion_correction: true # We do not need to perform lens distortion correction for calibration patterns
phase_shift_with_tpu:
  number_phases_horizontal: 19
  number_phases_vertical: 12
  average_intensity: 0.6
  modulation_intensity: 0.4
  shading_threshold: 30
two_plus_one_with_tpu:
  number_phases_horizontal: 19
  number_phases_vertical: 12
  average_intensity: 0.6
  modulation_intensity: 0.4
  shading_threshold: 30
